const express = require("express");
const routerUser = express.Router();
const controlUser = require("../controllers/controlUser.js");
const authUser = require("../middlewares/authUser.js");
routerUser.post("/create-user", controlUser.createNewUser);
routerUser.post("/auth-user", authUser.createLogin);
routerUser.get("/get-user", authUser.userIsAuthentic, controlUser.getUser);
routerUser.get("/all", authUser.userIsAuthentic, controlUser.getAllUsers);
routerUser.post("/update-user", authUser.userIsAuthentic, controlUser.updateUser);
routerUser.delete("/delete-user/:emailUser", controlUser.deleteUser);
module.exports = routerUser;
